# Generated by Django 3.1.4 on 2021-01-05 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='test_all',
            new_name='P8사단',
        ),
        migrations.RenameModel(
            old_name='test',
            new_name='정보통신대대',
        ),
    ]
