# Generated by Django 3.1.4 on 2021-01-01 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210101_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataxx',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
