# Generated by Django 3.1.4 on 2021-01-05 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210105_1659'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='P8사단',
            new_name='제8기동사단',
        ),
    ]
