# Generated by Django 3.1.4 on 2021-01-06 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210105_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='제50포병대대',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.제8기동사단')),
            ],
        ),
    ]
