# Generated by Django 3.1.4 on 2021-01-06 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_제50포병대대'),
    ]

    operations = [
        migrations.CreateModel(
            name='참모처',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.제8기동사단')),
            ],
        ),
        migrations.CreateModel(
            name='직할공병대대',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.제8기동사단')),
            ],
        ),
        migrations.CreateModel(
            name='제95포병대대',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.제8기동사단')),
            ],
        ),
        migrations.CreateModel(
            name='의무대',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.제8기동사단')),
            ],
        ),
        migrations.CreateModel(
            name='본부대',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.제8기동사단')),
            ],
        ),
        migrations.CreateModel(
            name='군사경찰대',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.제8기동사단')),
            ],
        ),
    ]
