# Generated by Django 3.1.4 on 2021-01-07 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_군사경찰대_본부대_의무대_제95포병대대_직할공병대대_참모처'),
    ]

    operations = [
        migrations.CreateModel(
            name='질문지',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('부대명', models.CharField(max_length=200)),
                ('Q1', models.CharField(max_length=200)),
                ('Q2', models.CharField(max_length=200)),
                ('Q3', models.CharField(max_length=200)),
                ('Q4', models.CharField(max_length=200)),
                ('Q5', models.CharField(max_length=200)),
                ('Q6', models.CharField(max_length=200)),
                ('Q7', models.CharField(max_length=200)),
                ('Q8', models.CharField(max_length=200)),
                ('Q9', models.CharField(max_length=200)),
                ('Q10', models.CharField(max_length=200)),
            ],
        ),
    ]
